name: 'Setup'
description: 'Setup Node.js and install dependencies with caching'

runs:
  using: 'composite'
  steps:
    - name: 🔧 Setup Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Restore node_modules cache
      id: cache-nodemodules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    - name: Install dependencies (if cache miss)
      if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash

    - name: Dependencies ready
      run: |
        if [[ "${{ steps.cache-nodemodules.outputs.cache-hit }}" == "true" ]]; then
          echo "Dependencies restored from cache"
        else
          echo "Dependencies installed and cached"
        fi
        echo "Node.js version: $(node --version)"
        echo "npm version: $(npm --version)"
      shell: bash
