name: 'CI Summary'
description: 'CI pipeline summary report'

inputs:
  install-dependencies-result:
    description: 'Result of install-dependencies job'
    required: true
  linting-result:
    description: 'Result of linting job'
    required: true
  test-result:
    description: 'Result of test job'
    required: true
  security-result:
    description: 'Result of security job'
    required: true
  build-result:
    description: 'Result of build job'
    required: true
  github-event-name:
    description: 'GitHub event name'
    required: true
  github-event-number:
    description: 'GitHub event number (for PRs)'
    required: false
  github-base-ref:
    description: 'GitHub base ref (for PRs)'
    required: false
  github-ref-name:
    description: 'GitHub ref name'
    required: true
  default-branch:
    description: 'Repository default branch'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Generate CI Summary
      shell: bash
      run: |
        # Determine if this is the default/primary branch
        DEFAULT_BRANCH="${{ inputs.default-branch }}"
        CURRENT_BRANCH="${{ inputs.github-ref-name }}"

        if [[ "${{ inputs.github-event-name }}" == "pull_request" ]]; then
          echo "## F1 World Champions PR Validation Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Pull Request:** #${{ inputs.github-event-number }}" >> $GITHUB_STEP_SUMMARY
          echo "**Target Branch:** ${{ inputs.github-base-ref }}" >> $GITHUB_STEP_SUMMARY
          if [[ "${{ inputs.github-base-ref }}" == "$DEFAULT_BRANCH" ]]; then
            echo "**Type:** Merging to ${{ inputs.github-base-ref }} (default)" >> $GITHUB_STEP_SUMMARY
          else
            echo "**Type:** Merging to ${{ inputs.github-base-ref }} (feature)" >> $GITHUB_STEP_SUMMARY
          fi
        else
          echo "## F1 World Champions Post-Merge Validation" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Branch:** ${{ inputs.github-ref-name }}" >> $GITHUB_STEP_SUMMARY
          if [[ "$CURRENT_BRANCH" == "$DEFAULT_BRANCH" ]]; then
            echo "**Type:** ${{ inputs.github-ref-name }} (default branch)" >> $GITHUB_STEP_SUMMARY
          else
            echo "**Type:** ${{ inputs.github-ref-name }} (feature branch)" >> $GITHUB_STEP_SUMMARY
          fi
        fi
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "###  Stage Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Stage | Status |" >> $GITHUB_STEP_SUMMARY
        echo "|-------|--------|" >> $GITHUB_STEP_SUMMARY
        echo "|  Dependencies | ${{ inputs.install-dependencies-result == 'success' && '✅ Success' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
        echo "|  Linting | ${{ inputs.linting-result == 'success' && '✅ Success' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
        echo "|  Testing | ${{ inputs.test-result == 'success' && '✅ Success' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
        echo "|  Security| ${{ inputs.security-result == 'success' && '✅ Success' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
        echo "|  Build | ${{ inputs.build-result == 'success' && '✅ Success' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

        echo "###  Overall Status" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [[ "${{ inputs.install-dependencies-result }}" == "success" && "${{ inputs.linting-result }}" == "success" && "${{ inputs.test-result }}" == "success" && "${{ inputs.security-result }}" == "success" && "${{ inputs.build-result }}" == "success" ]]; then
          if [[ "${{ inputs.github-event-name }}" == "pull_request" ]]; then
            echo "All checks passed! PR is ready for merge into ${{ inputs.github-base-ref }}" >> $GITHUB_STEP_SUMMARY
          else
            echo "Branch ${{ inputs.github-ref-name }} is healthy ✅" >> $GITHUB_STEP_SUMMARY
          fi
        else
          if [[ "${{ inputs.github-event-name }}" == "pull_request" ]]; then
            echo "Some checks failed. Please fix issues before merging into ${{ inputs.github-base-ref }} ❗" >> $GITHUB_STEP_SUMMARY
          else
            echo "Post-merge validation failed! Branch ${{ inputs.github-ref-name }} needs attention ❗" >> $GITHUB_STEP_SUMMARY
          fi
        fi
