name: 'Setup Environment'
description: 'Sets up Node.js, handles node_modules cache, and installs dependencies'
outputs:
  cache-hit:
    description: 'Whether the cache was hit'
    value: ${{ steps.cache-node-modules.outputs.cache-hit }}
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Cache/Restore node_modules
      id: cache-node-modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ github.head_ref || github.ref_name }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install Dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci
