name: Branch Protection

on:
  push:
    branches: [main, develop]

jobs:
  block-direct-push:
    name: 🚫 Block Direct Push
    runs-on: ubuntu-latest

    steps:
      - name: 🚫 Block direct push to protected branch
        run: |
          echo "::error::🚫 Direct pushes to main/develop are not allowed!"
          echo "::error::Please use the proper workflow:"
          echo "::error::1. Create a feature branch: git checkout -b feature/your-feature"
          echo "::error::2. Push your changes: git push origin feature/your-feature"
          echo "::error::3. Create a Pull Request on GitHub"
          echo "::error::4. Wait for CI checks to pass"
          echo "::error::5. Merge through GitHub after approval"
          exit 1
